# Generated by Django 6.0.2 on 2026-03-20 20:50

import django.contrib.postgres.indexes
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='منطقه')),
            ],
        ),
        migrations.CreateModel(
            name='BoardOfTrusteeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardOfTrustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('board_of_Trustee_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_of_Trustee_category', to='excel_app.boardoftrusteecategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ناحیه')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='excel_app.area')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='excel_app.subarea')),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], default=None, max_length=10, null=True, verbose_name='جنسیت')),
                ('status', models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال'), ('درحال بررسی', 'درحال بررسی'), ('رزرو', 'رزرو')], default='درحال بررسی', max_length=20, null=True, verbose_name='وضعیت')),
                ('edit_time', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='زمان آخرین ویرایش')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('national_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ملی')),
                ('is_verified', models.BooleanField(default=False, verbose_name='احرازهویت شده')),
                ('birth_certificate_number', models.CharField(blank=True, null=True, verbose_name='شماره شناسنامه')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل')),
                ('social_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل اجتماعی')),
                ('landline_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('neighborhood_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع سکونت در محله')),
                ('manager_engagement', models.CharField(blank=True, max_length=100, null=True, verbose_name='بکارگیری مدیر محله')),
                ('president_or_vice', models.CharField(blank=True, max_length=100, null=True, verbose_name='رئیس - نایب رئیس')),
                ('election_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتخابات')),
                ('election_letter_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره نامه انتخابات')),
                ('decree_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره حکم')),
                ('decree_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ حکم')),
                ('decree_delivery_to_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='تحویل حکم به منطقه')),
                ('decree_delivery_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل حکم به منطقه')),
                ('decree_notes', models.TextField(blank=True, null=True, verbose_name='توضیحات حکم')),
                ('neighborhood_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس سرای محله')),
                ('postal_code_neighborhood', models.CharField(blank=True, max_length=20, null=True, verbose_name='کدپستی سرای محله')),
                ('phone_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن 1 سرای محله')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن 2 سرای محله')),
                ('phone_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن 3 سرای محله')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='نمابر')),
                ('member_letter_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره نامه معرفی معتمدین از طرف عضو ستاد')),
                ('member_letter_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ نامه معرفی معتمدین از طرف عضو ستاد')),
                ('mayor_letter_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره نامه معرفی معتمدین به شهردار تهران')),
                ('mayor_letter_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ نامه معرفی به شهردار تهران')),
                ('zakani_letter_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره نامه صدور حکم معتمدین به زاکانی')),
                ('zakani_letter_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ نامه صدور حکم معتمدین به زاکانی')),
                ('supervision_request_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره استعلام از دستگاه نظارتی')),
                ('supervision_request_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ استعلام از دستگاه نظارتی')),
                ('supervision_reply_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره نامه جوابیه دستگاه نظارتی')),
                ('supervision_reply_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ نامه جوابیه دستگاه نظارتی')),
                ('supervision_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت نظارتی')),
                ('decree_issued', models.CharField(blank=True, max_length=100, null=True, verbose_name='صدور حکم')),
                ('bonus_1403', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='پرداخت عیدی 1403')),
                ('bonus_1403_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پرداخت 1403')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='حساب بانک شهر')),
                ('bonus_1404', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='عیدی 1404')),
                ('bonus_notes', models.TextField(blank=True, null=True, verbose_name='توضیحات پرداخت')),
                ('board_of_trustees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='excel_app.boardoftrustee', verbose_name='هیئت امناء')),
                ('certificate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='excel_app.certificatetype', verbose_name='نوع مدرک تحصیلی')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_fields', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='excel_app.neighborhood', verbose_name='محله')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='excel_app.subarea', verbose_name='ناحیه')),
            ],
        ),
        migrations.AddConstraint(
            model_name='boardoftrustee',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_board_member_name'),
        ),
        migrations.AddConstraint(
            model_name='subarea',
            constraint=models.UniqueConstraint(fields=('area', 'name'), name='unique_subarea_per_area'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(fields=('sub_area', 'name'), name='unique_neighborhood_per_subarea'),
        ),
        migrations.AddIndex(
            model_name='fields',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='fields_first_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='fields',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='fields_last_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
